version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app #optional, for development purposes
    environment:
      - DB_HOST=postgres #referencing the postgres container.
      - DB_NAME=blog
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_PORT=5432
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src #optional, for development purposes
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api #connecting to the backend container
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blog
    volumes:
      - postgres-data:/var/lib/postgresql/data #persisting data.

volumes:
  postgres-data: