name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Deploy Backend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: your-backend-app-name
          heroku_email: your-heroku-email@example.com
          usedocker: true

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Heroku CLI
        run: |
          wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Deploy Frontend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: your-frontend-app-name
          heroku_email: your-heroku-email@example.com
          usedocker: true