name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
          
      - name: Build Docker Image (Backend)
        run: |
          docker build -t registry.heroku.com/blog-backend-app/web -f backend/Dockerfile .

      - name: Deploy Backend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: blog-backend-app
          heroku_email: lobodaroman777@gmail.com
          usedocker: true

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Heroku CLI
        run: |
          wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Build Docker Image (Frontend)
        run: |
          docker build -t registry.heroku.com/your-frontend-app-name/client -f frontend/Dockerfile .

      - name: Deploy Frontend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: blog-frontend-app
          heroku_email: lobodaroman777@gmail.com
          usedocker: true
          